plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = neoforge_version

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
}

repositories {
    mavenLocal()
}

dependencies {
}

jar {
    manifest {
        attributes([
                'Implementation-Title'    : mod_name,
                'Implementation-Version'  : version,
                'Implementation-Vendor'   : mod_authors,
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "BreakInBlocks"
            url = version.toString().endsWith("-SNAPSHOT") ?
                "https://maven.breakinblocks.com/snapshots" :
                "https://maven.breakinblocks.com/releases"
            credentials {
                username = System.getenv("MAVEN_USER") ?: ""
                password = System.getenv("MAVEN_TOKEN") ?: ""
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
