org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.77

mod_id=whysoslow
mod_name=WhySoSlow
mod_version=1.0.4
mod_group=com.breakinblocks.whysoslow
mod_authors=BreakInBlocks
mod_description=Extremely detailed performance analysis of mods during load time, world loading, and world generation.
