org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.0
mappings_channel=official
mappings_version=1.20.1

mod_id=whysoslow
mod_name=WhySoSlow
mod_version=1.0.0
mod_group=com.breakinblocks.whysoslow
mod_authors=BreakInBlocks
mod_description=Extremely detailed performance analysis of mods during load time, world loading, and world generation.
